name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 1.8.2
author: "Rive Team <info@rive.app>"
homepage: https://github.com/2d-inc/Flare-Flutter
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flare_dart:
    git: 
      url: git://github.com/2d-inc/Flare-Flutter.git
      ref: dev
      path: flare_dart
dev_dependencies:
  flutter_test:
    sdk: flutter